(part "ECH-U1C104JX5"
    (packageRef "ECHU_G3_18")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "667-ECH-U1C104JX5")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/ECH-U1C104JX5?qs=b%252BB9euYP3EMLLnBUsHao4g%3D%3D")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "ECH-U1C104JX5")
    (property "Description" "Plastic Film Capacitor, Stacked metallized PPS film as dielectric with simple mold-less construction")
    (property "Datasheet_Link" "http://industrial.panasonic.com/cdbs/www-data/pdf/RDI0000/ABD0000C173.pdf")
    (property "symbolName1" "ECH-U1C104JX5")
)
