(part "MIC5317-1_2YM5-TR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "998-MIC5317-1.2YM5TR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MIC5317-12YM5-TR?qs=U6T8BxXiZAUk7GFYLwZxxw%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MIC5317-1.2YM5-TR")
    (property "Description" "LDO Voltage Regulators Single LDO, Hi-Perf. 150mA, 1.2 Vout")
    (property "Datasheet_Link" "http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en579427")
    (property "symbolName1" "MIC5317-1_2YM5-TR")
)
