(part "C2012X7R1E105K125AB"
    (packageRef "C2012_Commercial")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "810-C2012X7R1E105K")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/C2012X7R1E105K125AB?qs=NRhsANhppD%252Buy2B2F1KPNA%3D%3D")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "C2012X7R1E105K125AB")
    (property "Description" "0805 X7R ceramic capacitor 25V 1uF TDK C2012 C 1uF Ceramic Multilayer Capacitor, 25 V dc X7R Dielectric +/-10% SMD")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/capacitor/ceramic/mlcc/catalog/mlcc_commercial_general_en.pdf")
    (property "symbolName1" "C2012X7R1E105K125AB")
)
