(part "54101-S0803LF"
    (packageRef "54101S0803LF")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "649-54101-S0803LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Amphenol-FCI/54101-S0803LF?qs=iiM6sTJtPEc921tw16XaKg%3D%3D")
    (property "Manufacturer_Name" "Amphenol Communication Solutions")
    (property "Manufacturer_Part_Number" "54101-S0803LF")
    (property "Description" "BergStik, Board to Board connector, Unshrouded vertical Header, Through Hole, Single Row, 3 Positions, 2.54 mm Pitch.")
    (property "Datasheet_Link" "https://cdn.amphenol-cs.com/media/wysiwyg/files/drawing/54101.pdf")
    (property "symbolName1" "54101-S0803LF")
)
